name:                mpi-definite-matrices
version:             0.1.0.0
github:              "viluon/mpi-definite-matrices"
license:             BSD3
author:              "Andrew Kvapil"
maintainer:          "viluon@pm.me"
copyright:           "2021 Andrew Kvapil"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/viluon/mpi-definite-matrices#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix
- attoparsec
- text

library:
  source-dirs: src

executables:
  mpi-definite-matrices-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mpi-definite-matrices

tests:
  mpi-definite-matrices-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mpi-definite-matrices
